url: https://titchimoto.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Richard Deane - Software Engineer Portfolio
email: titchimoto@gmail.com
description: "The personal portfolio website of Richard Deane, a full-stack software engineer residing in Portland, OR."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/titchimoto
  - title: linkedin
    url: http://linkedin.com/in/richardcdeane
  - title: github
    url: http://github.com/titchimoto

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
